language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
  - sudo apt-get install -qq -y xsltproc
# command to run tests
script: make test
