# default list of available public projects
DIS        = "projects/DIS"
# EXER     = "projects/EXER"
# GERMANIC = "projects/GERMANIC"
HMONGMIEN  = "projects/HMONGMIEN"
KIRANTI    = "projects/KIRANTI"
LOLOISH    = "projects/LOLOISH"
POLYNESIAN = "projects/POLYNESIAN"
ROMANCE    = "projects/ROMANCE"
SLAVIC     = "projects/SLAVIC"
VANUATU    = "projects/VANUATU"
