# projects configuration
DIS = "projects/DIS"
HMONGMIEN = "projects/HMONGMIEN"
LOLOISH = "projects/LOLOISH"
POLYNESIAN = "projects/POLYNESIAN"
ROMANCE = "projects/ROMANCE"
SLAVIC = "projects/SLAVIC"
TGTM = "/Users/johnlowe/GitHub/RE-Tamangish-files/TGTM"
VANUATU = "projects/VANUATU"
KIRANTI = "projects/KIRANTI"
