TGTM       = "/Users/johnlowe/GitHub/RE-Tamangish-files/TGTM"
TGTM94SETS = "/Users/johnlowe/GitHub/RE-Tamangish-files/TGTM94SETS"
DEMO93     = "/Users/johnlowe/GitHub/RE-Tamangish-files/DEMO93"

DIS        = "projects/DIS"
# EXER     = "projects/EXER"
# GERMANIC = "projects/GERMANIC"
HMONGMIEN  = "projects/HMONGMIEN"
KIRANTI    = "projects/KIRANTI"
LOLOISH    = "projects/LOLOISH"
POLYNESIAN = "projects/POLYNESIAN"
ROMANCE    = "projects/ROMANCE"
SLAVIC     = "projects/SLAVIC"
VANUATU    = "projects/VANUATU"
